# Generated by Django 3.1.1 on 2020-10-20 04:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20201019_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='movie',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
